sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - npm install -g bower
  - npm install -g gulp

before_script:
  - gradle npmInstall

script:
  - gradle docker


after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push lumue/getdown:download-tasks-SNAPSHOT
  
