name: getdown_client
description: A sample web application
environment:
  sdk: '>=1.2.0 <2.0.0'
dependencies:
  core_elements: '>=0.3.0+1'
  http: any
  json_object: any
  paper_elements: any
  polymer: '>=0.15.0'
dev_dependencies:
  unittest: any
transformers:
- polymer:
    entry_points:
    - web/index.html
